name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build.yml
    with:
      push: true
      tags: "ghcr.io/chrisabird/servo:${{ github.ref_name }},ghcr.io/chrisabird/servo:latest"
    secrets: inherit
